#!/bin/sh
FAHOME=/usr/share/forcedattack2
if [ ! -f ~/.4stattackrc ]; then
	cp $FAHOME/settings.ini ~/.4stattackrc
fi
if [ -x $FAHOME/4stattack.py ]; then
	$FAHOME/4stattack.py -ini ~/.4stattackrc
fi

